# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 037a6cbb30b14eab450827fc6610429b8055d4d8cd26252cbeeefb8c3721e2003df2985867cc818002a53531f93cd233876303852c875002c968ae019f483c64

test:
  secret_key_base: 051ede699f74e9be2fdf68671332cbc3e136ca71869dde64c8972743ec0340fc957259485cd13063cf1786d928ff942b2880babb6584d7446800f8adc3fb98c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
